// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDre2z9wud5A9j4J3hByk7JSTckLw8ts',
    appId: '1:837038293145:web:d47c06e42164a40c417808',
    messagingSenderId: '837038293145',
    projectId: 'com-tiinver',
    authDomain: 'com-tiinver.firebaseapp.com',
    storageBucket: 'com-tiinver.appspot.com',
    measurementId: 'G-BG9JK2EZ3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0vjSyPeJQVwbcd8MRHY8e3uWgua9dv6o',
    appId: '1:837038293145:android:5cb4f4c1642bc859417808',
    messagingSenderId: '837038293145',
    projectId: 'com-tiinver',
    storageBucket: 'com-tiinver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmXS0sHJTG-Ydmio1vQCyB35sud8d2Lfg',
    appId: '1:837038293145:ios:42c762065c653c4d417808',
    messagingSenderId: '837038293145',
    projectId: 'com-tiinver',
    storageBucket: 'com-tiinver.appspot.com',
    iosBundleId: 'com.tiinver.tiinverProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmXS0sHJTG-Ydmio1vQCyB35sud8d2Lfg',
    appId: '1:837038293145:ios:42c762065c653c4d417808',
    messagingSenderId: '837038293145',
    projectId: 'com-tiinver',
    storageBucket: 'com-tiinver.appspot.com',
    iosBundleId: 'com.tiinver.tiinverProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSDre2z9wud5A9j4J3hByk7JSTckLw8ts',
    appId: '1:837038293145:web:88c7f7944588f34b417808',
    messagingSenderId: '837038293145',
    projectId: 'com-tiinver',
    authDomain: 'com-tiinver.firebaseapp.com',
    storageBucket: 'com-tiinver.appspot.com',
    measurementId: 'G-QP2QL6WWD6',
  );
}
